var imgPreloadArray = new Array("images/gray_dot_old.png",
	"images/loading.gif",
	"images/menu_btn.png",
	"images/next_btn.png",
	"images/prev_btn.png",
	"images/table_btn.png",
	"images/arrow.png",
	"images/check_btn.png",
	"images/checkbox.png",
	"images/dot.png",
	"images/figure-7-27.jpg",
	"images/figure-7-28.jpg",
	"images/figure-7-29.jpg",
	"images/figure-10-8.jpg",
	"images/figure-10-27-a.jpg",
	"images/figure-10-27-b.jpg",	
	"images/ped310.jpg",
	"images/ped311.jpg",
	"images/ped312.jpg",
	"images/ped313.jpg",
	"images/ped320.jpg",
	"images/ped321.jpg",
	"images/ped330.jpg",
	"images/ped331.jpg",
	"images/ped332.jpg",
	"images/ped333.jpg",
	"images/ped334.jpg",
	"images/ped340.jpg",
	"images/ped350.jpg",
	"images/ped351.jpg",
	"images/ped352.jpg",
	"images/ped360.jpg",
	"images/ped361.jpg",
	"images/ped362.jpg",
	"images/ped363.jpg",
	"images/ped370.jpg",
	"images/ped371.jpg",
	"images/ped372.jpg",
	"images/ped380.jpg",
	"images/ped381.jpg",
	"images/ped390.jpg",
	"images/ped3100.jpg",
	"images/ped3101.jpg",
	"images/ped3110.jpg",
	"images/ped3111.jpg",
	"images/ped3112.jpg",
	"images/ped3113.jpg",
	"images/ped3114.jpg",
	"images/ped3120.jpg",
	"images/ped3121.jpg",
	"images/ped3130.jpg",
	"images/ped3131.jpg",
	"images/ped3132.jpg",
	"images/ped3140.jpg",
	"images/ped3141.jpg",
	"images/placeholder.jpg",
	"images/placeholder.png",
	"images/gray_dot.png");
var imagePreCount = 0;
for(var pId = 0; pId < imgPreloadArray.length; pId++)
{
	var img = new Image();
	img.onload = imagePreloaded;
	img.src = imgPreloadArray[pId];
}
function imagePreloaded()
{
	imagePreCount++;
}