var imgPreloadArray = new Array("images/gray_dot_old.png",
	"images/loading.gif",
	"images/menu_btn.png",
	"images/next_btn.png",
	"images/prev_btn.png",
	"images/table_btn.png",
	"images/arrow.png",
	"images/check_btn.png",
	"images/checkbox.png",
	"images/dot.png",
	"images/cns210.jpg",
	"images/cns211.jpg",
	"images/cns212.jpg",
	"images/cns220.jpg",
	"images/cns221.jpg",
	"images/cns222.jpg",
	"images/cns223.jpg",
	"images/cns230.jpg",
	"images/cns231.jpg",
	"images/cns240.jpg",
	"images/cns241.jpg",
	"images/cns242.jpg",
	"images/cns250.jpg",
	"images/cns251.jpg",
	"images/cns260.jpg",
	"images/cns261.jpg",
	"images/cns262.jpg",
	"images/cns263.jpg",
	"images/cns270.jpg",
	"images/cns271.jpg",
	"images/cns272.jpg",
	"images/cns273.jpg",
	"images/cns274.jpg",
	"images/cns275.jpg",
	"images/cns276.jpg",
	"images/cns277.jpg",
	"images/cns280.jpg",
	"images/cns281.jpg",
	"images/cns282.jpg",
	"images/cns283.jpg",
	"images/cns284.jpg",
	"images/cns285.jpg",
	"images/cns286.jpg",
	"images/cns287.jpg",
	"images/cns288.jpg",
	"images/cns290.jpg",
	"images/cns291.jpg",
	"images/cns292.jpg",
	"images/cns293.jpg",
	"images/cns294.jpg",
	"images/cns2100.jpg",
	"images/cns2101.jpg",
	"images/cns2102.jpg",
	"images/cns2103.jpg",
	"images/cns2110.jpg",
	"images/cns2111.jpg",
	"images/cns2112.jpg",
	"images/cns2113.jpg",
	"images/figure-28-10.jpg",
	"images/figure-28-3.jpg",
	"images/figure-28-3.jpg",
	"images/placeholder.jpg",
	"images/placeholder.png",
	"images/gray_dot.png");
var imagePreCount = 0;
for(var pId = 0; pId < imgPreloadArray.length; pId++)
{
	var img = new Image();
	img.onload = imagePreloaded;
	img.src = imgPreloadArray[pId];
}
function imagePreloaded()
{
	imagePreCount++;
}