var imgPreloadArray = new Array("images/gray_dot_old.png",
	"images/loading.gif",
	"images/menu_btn.png",
	"images/next_btn.png",
	"images/prev_btn.png",
	"images/table_btn.png",
	"images/arrow.png",
	"images/check_btn.png",
	"images/checkbox.png",
	"images/dot.png",
	"images/Figure 17-49.jpg",
	"images/Figure 17-50.jpg",
	"images/gas610.jpg",
	"images/gas611.jpg",
	"images/gas612.jpg",
	"images/gas620.jpg",
	"images/gas621.jpg",
	"images/gas622.jpg",
	"images/gas623.jpg",
	"images/gas624.jpg",
	"images/gas630.jpg",
	"images/gas631.jpg",
	"images/gas632.jpg",
	"images/gas640.jpg",
	"images/gas641.jpg",
	"images/gas642.jpg",
	"images/gas643.jpg",
	"images/gas644.jpg",
	"images/gas650.jpg",
	"images/gas651.jpg",
	"images/gas652.jpg",
	"images/gas660.jpg",
	"images/gas661.jpg",
	"images/gas662.jpg",
	"images/gas670.jpg",
	"images/gas671.jpg",
	"images/gas672.jpg",
	"images/gas680.jpg",
	"images/gas681.jpg",
	"images/gas682.jpg",
	"images/gas683.jpg",
	"images/gas684.jpg",
	"images/gas685.jpg",
	"images/gas690.jpg",
	"images/gas691.jpg",
	"images/gas692.jpg",
	"images/gas6100.jpg",
	"images/gas6101.jpg",
	"images/gas6102.jpg",
	"images/neo210.jpg",
	"images/neo220.jpg",
	"images/neo230.jpg",
	"images/neo240.jpg",
	"images/neo250.jpg",
	"images/neo260.jpg",
	"images/neo270.jpg",
	"images/neo280.jpg",
	"images/neo290.jpg",
	"images/neok150.jpg",
	"images/neok160.jpg",
	"images/neok170.jpg",
	"images/neok180.jpg",
	"images/neok190.jpg",
	"images/neok1100.jpg",
	"images/neok1120.jpg",
	"images/familialadenomatouspolyposissyndrome.mp4",
	"images/familialadenomatouspolyposissyndrome.webm",
	"images/gas6103.jpg",
	"images/gas6104.jpg",
	"images/placeholder.jpg",
	"images/placeholder.png",
	"images/gray_dot.png");
var imagePreCount = 0;
for(var pId = 0; pId < imgPreloadArray.length; pId++)
{
	var img = new Image();
	img.onload = imagePreloaded;
	img.src = imgPreloadArray[pId];
}
function imagePreloaded()
{
	imagePreCount++;
}