var imgPreloadArray = new Array("images/gray_dot_old.png",
	"images/loading.gif",
	"images/menu_btn.png",
	"images/next_btn.png",
	"images/prev_btn.png",
	"images/table_btn.png",
	"images/arrow.png",
	"images/check_btn.png",
	"images/checkbox.png",
	"images/dot.png",
	"images/Figure 13-28.jpg",
	"images/hem710.jpg",		
	"images/hem720.jpg",
	"images/hem721.jpg",
	"images/hem722.jpg",
	"images/hem723.jpg",
	"images/hem724.jpg",
	"images/hem730.jpg",
	"images/hem731.jpg",
	"images/hem740.jpg",
	"images/hem741.jpg",
	"images/hem742.jpg",
	"images/hem743.jpg",
	"images/hem750.jpg",
	"images/hem760.jpg",
	"images/hem761.jpg",
	"images/hem762.jpg",
	"images/hem763.jpg",
	"images/hem764.jpg",
	"images/hem765.jpg",
	"images/hem770.jpg",
	"images/hem771.jpg",
	"images/hem772.jpg",
	"images/hem773.jpg",
	"images/hem774.jpg",
	"images/hem775.jpg",
	"images/hem780.jpg",
	"images/hem781.jpg",
	"images/hem782.jpg",
	"images/hem783.jpg",
	"images/hem784.jpg",
	"images/hem790.jpg",
	"images/hem791.jpg",
	"images/hem792.jpg",
	"images/hem793.jpg",
	"images/hem794.jpg",
	"images/hem7100.jpg",
	"images/hem7101.jpg",
	"images/hem7102.jpg",
	"images/hem7110.jpg",
	"images/hem7111.jpg",
	"images/hem7112.jpg",
	"images/hem7120.jpg",
	"images/hem7121.jpg",
	"images/hem7122.jpg",
	"images/hem7123.jpg",
	"images/hem7124.jpg",
	"images/placeholder.jpg",
	"images/placeholder.png",
	"images/gray_dot.png");
var imagePreCount = 0;
for(var pId = 0; pId < imgPreloadArray.length; pId++)
{
	var img = new Image();
	img.onload = imagePreloaded;
	img.src = imgPreloadArray[pId];
}
function imagePreloaded()
{
	imagePreCount++;
}